### ISSUE TITLE
camel GET doesn't have message body yet datasonnet still expects a body

### ISSUE THREAD

**Issue by adrianhsieh** [datasonnet/datasonnet-mapper#102]
So throws exception like:

ujson.IncompleteParseException: exhausted input

And workaround of setting an empty body becomes needed.

Fix should be datasonnet smart enough to realize body not present and handle accordingly.

**Comment by javaduke** [comment]
This should be addressed as part of the Camel Datasonnet component, see https://issues.apache.org/jira/browse/CAMEL-18292

**Comment by javaduke** [comment]
This was addressed by the Camel component, no further action needed on our side.
