### ISSUE TITLE
std.get()

### ISSUE THREAD

**Issue by jeremyross** [datasonnet/datasonnet-mapper#110]
I'm having trouble using std.get(). Is it available via datasonnet? jsonnet docs say it was added in 0.18.0, but it's not clear to me what version of jsonnet is supported in datasonnet.

**Comment by javaduke** [comment]
hi Jeremy, yes, the `std.get()` is not implemented in Datasonnet yet - I can schedule it for the next release but it may take a while. In the meantime, you can implement your own `get` function as a part of your mapping.

**Comment by javaduke** [comment]
The new version 2.5 includes Std.get() as well as other missing Std functions.
