### ISSUE TITLE
Jakarta EE compatible release

### ISSUE THREAD

**Issue by davsclaus** [datasonnet/datasonnet-mapper#112]
Hi

Apache Camel has datasonnet integration and we are working on Camel v4 which is upgrading to JEE 10 (javax -> jakarta) and we can see that camel-datasonnet fails with datasonnet 2.2.0 due to

```

java.lang.NoClassDefFoundError: javax/xml/bind/JAXBElement

	at com.datasonnet.plugins.DefaultJavaFormatPlugin.<clinit>(DefaultJavaFormatPlugin.java:60)
	at com.datasonnet.spi.DataFormatService.<clinit>(DataFormatService.java:30)
	at com.datasonnet.MapperBuilder.<init>(MapperBuilder.java:38)

```

I wonder if you plan to do a release that supports Jakarta EE spec or can find a way to make a release support both javax and jakarta ee, eg its in this code

```
module.addSerializer(JAXBElement.class, new JAXBElementSerializer());
```

Maybe you can try to detect if its javax or jakarta ee for that serializer

**Comment by davsclaus** [comment]
Link to Apache Camel JIRA ticket: https://issues.apache.org/jira/browse/CAMEL-18907

**Comment by javaduke** [comment]
Hmm, yes, this feature was added so that Datasonnet can support and map wsdl-generated objects. I'm honestly not sure what would be the best course of action here, because we need to maintain backwards compatibility.

**Comment by davsclaus** [comment]
Yeah I am not sure how other projects do it, thought I have seen some use maven shade plugin to search/replace and build a -jakarta JAR ala
https://github.com/apache/shiro/pull/522/files

**Comment by javaduke** [comment]
Yep, thanks, Claus, I guess I will have to release two separate versions, at least for the time being.
What is the deadline for this? There are several outstanding issues I would like to address in the new release, just want to know how much time can I spend on them.

**Comment by davsclaus** [comment]
Camel 4.0 GA is April/May but if we are really speedy then it may be as fast as late March

**Comment by davsclaus** [comment]
But camel-datasonnet can be added back to 4.x when its jakarta ready, eg in 4.1 or 4.2 etc.

**Comment by javaduke** [comment]
Ah, good, then I guess I have time. I'll try to wrap up everything in two-three weeks from now, the goal is to have a new release by February 1st (or earlier, if I'm lucky :)

**Comment by javaduke** [comment]
Well, I addressed all the outstanding issues I mentioned, but I still cannot figure out how to make a release. The problem is that the datasonnet Java code imports `javax.xml.bind.JAXBElement` so even if I add jakarta 4 as a dependency and use the shade plugin, the resulting jar won't be compatible with both versions of Camel. Seems like I need to find a way to maintain two separate submodules...

**Comment by javaduke** [comment]
OK, the new version is out there, the version number is `2.5-jakarta4`.
