### ISSUE TITLE
Modify data transformation functions to take Header

### ISSUE THREAD

**Issue by fugu13** [datasonnet/datasonnet-mapper#53]
Right now version is being threaded through as a mediatype parameter, but we should thread the header object through instead and access it on that

**Comment by jam01** [comment]
Oh I'm now seeing that it's the XML Plugin where the header is used currently... :thinking:

**Comment by jam01** [comment]
I initially thought it was in the functions where the version was being used...

So giving this particular issue some thought, I think the best way to handle XML read backwards compatibility is to introduce what https://github.com/MS3Inc/datasonnet-mapper/issues/17 is about.

A param like `badgerfish=simple` `badgerfish=full`, with simple being the default. Full would be what v2 does currently. Simple would concatenate all text into a single `$`, including CData.

Would that solve the problem?

In the general use case though, it should be fine to _also_ pass the header through to the plugins when doing the acutal `read` and `write`. I can work on that. I actually had an use case where I need the dataformat service when doing `read` and `write` so I might just send a PR with both.

**Comment by jam01** [comment]
Actually... thinking about this some more (sorry) I don't think we _should_ pass the header to the plugins. I think it violates the encapsulation that (`Plugin`, `MediaType`) is designed to have.

The idea is that each plugin will declare what `MediaType`s and media type parameters it supports that modify default reading/writing.  So for the XML use case I think if the `badgerfish=simple` is not sufficient then we could do `badgerfish=legacy`

**Comment by fugu13** [comment]
This is merged and in
