### ISSUE TITLE
Modify version checking to run future minor-versioned headers with a warning

### ISSUE THREAD

**Issue by fugu13** [datasonnet/datasonnet-mapper#63]
Major version headers will still be rejected

**Comment by JakeMHughes** [comment]
@fugu13 do we have a specific method in mind for handling minor versions data? for instance, in my mind a version 1.1 would be parsed the exact same way as a version 1.0 but with some extra stuff. So for me it would make sense to call the `parseHeader10` function to create the header then just update the created header however needed.

but, currently all the header variables are final

**Comment by fugu13** [comment]
There shouldn't be any need to modify the header after parsing, since what gets parsed is still the same. Version recognition just needs to be extended to accept 2.x (note: minor version could be any number of digits) and warn if x > 0.

The header structure should be modified to include major version and minor version as separate attributes, to make it easier for later code to check.

There's no need to recognize 1.x, only 1.0, since we've moved to the 2.x series and there will be nothing between 1.0 and 2.0, so we can be sure that is still an error.
