### ISSUE TITLE
quickstart link to plugin install broken

### ISSUE THREAD

**Issue by ksully-execute** [datasonnet/datasonnet-mapper#97]
on the quickstart
https://datasonnet.github.io/datasonnet-mapper/datasonnet/latest/quickstart.html#_installing_the_plugin
there's a link to 
Now, follow the directions for installing the plugin at IntelliJ Plugin.
but the link is invalid:
https://datasonnet.github.io/datasonnet-mapper/datasonnet/latest/quickstart.html#intellij:ROOT:index.adoc

**Comment by javaduke** [comment]
Done, the docs are updated

**Comment by ksully-execute** [comment]
Will review, thanks much javaduke
