### ISSUE TITLE
Warning in logs when using version=2.1 i header

### ISSUE THREAD

**Issue by henka-rl** [datasonnet/datasonnet-mapper#98]
When executing a script with this header: 
/** DataSonnet
version=2.1
input * application/json
output application/json
*/
using version 2.1.4 of Datasonnet I get this waring:
"WARNING: You are using a version that is still in development. The latest release version is: 2.0"
Shouldn't this warning be removed as 2.1.4 is the latest release?

**Comment by javaduke** [comment]
We differentiate between the library version and the language version - the latter is either `1.0` or `2.0` at the moment.
